### PR TITLE
Move login to a new jsx file

### PR DESCRIPTION
**Pull request by danielepo**

### CODE REVIEW

**Comment by g105b** [comment]
Wow you're putting loads of effort to this repo!

**Comment by danielepo** [comment]
Well, the idea is cool it out gives me opportunity to experiment with tech I have a chance to use at work. It would be nice to have more ppl contributing

**Comment by g105b** [comment]
I agree, well tell your friends and colleagues, I'll try to get some others contributing -- it'll be on the front page of Hacker News in no time!

**Comment by danielepo** [comment]
That would be really cool!

Il mer 1 feb 2017, 16:41 Greg Bowler <notifications@github.com> ha scritto:

**Pull request merged**
